title: Summary So Far
email: nancylees303@gmail.com
description: Learn by iterative writing
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.summarysofar.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nancylee713

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist

paginate: 10

permalink: /:year/:month/:day/:title

collections:
  projects:
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: category-tag-archive-layout
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-149413160-1"