# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Summary So Far
email: nancylees303@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn by iterative writing
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.summarysofar.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus:
  shortname: summarysofar
# twitter_username:
github_username:  nancylee713

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist

paginate: 10

permalink: /:year/:month/:day/:title

collections:
  projects:
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: category-tag-archive-layout
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-149413160-1"